### ISSUE TITLE
How you get receipt?

### ISSUE THREAD

**Issue by lexx02** [plehatron/receipt-validation#1]
Hi,
I have such issue - 
I need validate at my php-site itunes purchase by receipt ID.
At your library you use receipt, how does you get it?
Thanks.

**Comment by plehatron** [comment]
Hi,

Receipt is made available by the itunes server when a purchase is done in the iOS app. The app has to send this receipt to the server in order for the PHP app to parse it and verify it on the itunes server.

Hope this helps.

**Comment by lexx02** [comment]
Thanks, but my case is other.
User purchases app at Mac App Store.
Then he receives email with receipt id.
User registers at my site with this receipt id.
I need validate it.

**Comment by plehatron** [comment]
I see. I'm not sure how a receipt ID looks like because receipts that this lib validates look like the one here: https://gist.github.com/sauloarruda/2559455
Receipt is basically a base64 encoded binary data. Apple receipt validation service is explained here: https://developer.apple.com/library/ios/releasenotes/General/ValidateAppStoreReceipt/Chapters/ValidateRemotely.html

**Comment by lexx02** [comment]
Oh....
Thanks. I suggested that if I know receipt ID I can to know receipt.
And then use your library.
